spring.application.name=scrambleid

# Database setup
spring.datasource.url=jdbc:mysql://localhost:3306/scrambleid?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345678

# API starts with `/api`
server.servlet.context-path=/api

spring.jpa.hibernate.ddl-auto=update


jwt.secret=xaCrasLWr0phlCriJoK2?9pHab!P0l73swa?UPr?Hir-?Ovu+=tASTE5&H#branL
jwt.expiration=86400000
jwt.refresh-expiration=604800000